url: https://barriodelibros.github.io/
baseurl: /


# Site settings
title: Barrio de libros
email: info@barriodelibros.org
description: "Un barrio de microeditoriales insumisas."


# Team names, titles and social links

people:
- name: Contra escritura
  pic: 1
  position: 
  website: https://www.contraescritura.com/
     

- name: Orciny Press
  pic: 2
  position: 
  website: https://www.orcinypress.com/
   

- name: Amor de madre
  pic: 3
  position: 
  website: https://editorialamordemadre.com/
    

- name: Burro lector
  pic: 4
  position: 
  website: https://burrolector.com/
    

- name: Ménades
  pic: 5
  position: 
  website: https://menadeseditorial.com/
    

- name: Libros de la Vorágine
  pic: 6
  position: 
  website: https://lavoragine.org/

- name: La niña azul
  pic: 7
  position: 
  website: laninaazul.es
    

- name: biblioteca de Carfax
  pic: 8
  position: 
  website: https://labibliotecadecarfax.com/
    

- name: Esto no es Berlín
  pic: 9
  position: 
  website: https://www.estonoesberlin.com/

- name: Insólita
  pic: 10
  position: 
  website: https://insolitaeditorial.com/

- name: Aloha
  pic: 11
  position: 
  website: https://www.alohaeditorial.com/

- name: Horror vacui
  pic: 14
  position: 
  website: https://horror-vacui.es/

- name: SECC
  pic: 19
  position: 
  website: hhttps://edicionssecc.blogspot.com/  



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/barriolibros
  - title: facebook
    url:
 
  - title: instagram 
    url: https://www.instagram.com/barrio.libro/

  - title: github
    url: https://github.com/barriodelibros
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
