url: https://barriodelibros.github.io/
baseurl: /


# Site settings
title: Barrio de libros
email: info@barriodelibros.org
description: "Un barrio de microeditoriales insumisas."


# Team names, titles and social links
people:
- name: Contra escritura
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Orciny Press
  pic: 2
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Amor de madre
  pic: 3
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Burro lector
  pic: 4
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Ménades
  pic: 5
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Libros de la Vorágine
  pic: 6
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Índigo
  pic: 7
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Carfax
  pic: 8
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: ENEB
  pic: 9
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: Insólita
  pic: 10
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 11
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 12
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 13
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 14
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 15
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 16
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 17
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 18
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 19
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

- name: 
  pic: 20
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/barriolibros
  - title: facebook
    url:
 
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/barriodelibros
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
